### ISSUE TITLE
How about putting in inums before i18n_key?

### ISSUE THREAD

**Issue by ighrs** [alfa-jpn/inum#7]
With v4.0.1, Is `self.i18n_key` of REDME a failure to erase?
I would like to manage as follows because It is easy to classify data. 

``` yaml
ja:
  inums:
    anime_types:
      evangelion: 'エヴァンゲリオン'
      haruhi:     'ハルヒ'
      nyaruko:    '這いよれ！ニャル子さん'
```
